[package]
name = "rux-runtime"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
rux-core = { path = "../rux-core" }
parking_lot = { workspace = true }
thiserror = { workspace = true }
